### ISSUE TITLE
Crash on dying

### ISSUE THREAD

**Issue by BossCreeper81** [Lizard-Of-Oz/Inventorio#172]
The game crashes  on dying

1.19.2 Quilt

Crashlog: https://bytebin.lucko.me/s502lHZ7gf

**Comment by Lizard-Of-Oz** [comment]
It appears that a different mod tries to render something related to arrow items on the HUD while the player is dead, which leads to this crash. Which mod does that is unclear from the logs because of how injections/mixins work.

While it's that mod's fault, here's a potential hotfix:
[inventorio-1.19-fabric-1.8.5.zip](https://github.com/Lizard-Of-Oz/Inventorio/files/9483209/inventorio-1.19-fabric-1.8.5.zip)

**Comment by BossCreeper81** [comment]
Ok that was quick wtf.

Thanks a lot, that fixed it!
